version: '3.6'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    entrypoint: ["./apache-tomcat-6.0.20/bin/catalina.sh", "run"]