version: '3.6'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: CVE-2022-22978
    ports:
      - 8080:8080
      - 5005:5005
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "demo-0.0.1-SNAPSHOT.jar"]